apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-deployment
spec:
  selector:
    matchLabels:
      name: newtetris
  template:
    metadata:
      labels:
        name: newtetris
    spec:
      containers:
        - name: newtetris
          image: lrakai/tetris
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: tetris-service
spec:
  type: NodePort
  selector:
    name: newtetris
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
